# Generated by Django 2.1.7 on 2019-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user_password', models.CharField(max_length=254)),
                ('imei', models.CharField(max_length=64)),
                ('lock_password', models.CharField(max_length=32)),
                ('master_id', models.CharField(max_length=64)),
                ('master_password', models.CharField(max_length=32)),
            ],
        ),
    ]
