# Generated by Django 2.1.7 on 2019-05-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_masterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='master_password',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='master_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
