# Generated by Django 2.1.7 on 2019-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20190529_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='user_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
